name: d2haskell
version: 0.1.0.0
github: "githubuser/d2haskell"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

default-extensions:
    - OverloadedStrings

extra-source-files:
    - README.md
    - ChangeLog.md
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/d2haskell#readme>

dependencies:
    - base >= 4.7 && < 5
    - discord-haskell
    - emoji
    - unliftio
    - text
    - persistent-postgresql
    - monad-logger
    - persistent
    - transformers
    - persistent-template
    - mtl
    - dotenv
    - bytestring
    - text-show
    - time
    - rio
    - resourcet
library:
    source-dirs: src
    exposed-modules:
        - Core
        - Db.Migrations

executables:
    d2haskell-exe:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - d2haskell

tests:
    d2haskell-test:
        main: Spec.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - d2haskell
